const medicalTerms = [
    { word: "Abdomen", definition: "the part of the body located between the chest (thorax) and the hips."},
    { word: "Abdominal", definition: "relating to the abdomen; i.e., the belly or midsection." },
    { word: "Abdominal aorta", definition: "largest artery in the abdominal cavity." },
    { word: "Abdominoplasty", definition: "a surgical procedure to remove extra skin and fat from the abdomen." },
    { word: "Abortion", definition: "termination of pregnancy; removal of fetus or embryo before viability." },
    { word: "Acute", definition: "a condition that starts suddenly and is short-term." },
    { word: "Acidosis", definition: "a condition in which there is too much acid in the body fluids." },
    { word: "Adenomyosis", definition: "a condition where the tissue from the lining of the uterus grows into the uterine wall." },
    { word: "Adhesions", definition: "band of scar tissue that joins two internal body surfaces that are not usually connected." },
    { word: "Aetiology", definition: "study of the cause of disease" },
    { word: "Alopecia", definition: "a medical term for hair loss or baldness, and “areata” means that it occurs in small, random areas." },
    { word: "Amniocentesis", definition: "a procedure that removes amniotic fluid and cells from the uterus for testing or treatment; a prenatal test that can diagnose genetic disorders and other health issues in a fetus." },
    { word: "Amniotic fluid", definition: "a clear, yellowish, and odorless fluid that surrounds and protects a fetus during pregnancy." },
    { word: "Amniotic sac", definition: "the “bag of waters” that breaks during labor; a thin, tough, transparent pair of membranes that surround and protects the fetus in the womb." },
    { word: "Anaemia", definition: "low levels of healthy red blood cells; can cause tiredness or weakness." },
    { word: "Anaesthesia", definition: "use of medication to prevent pain during procedure or surgery; being numbed or put to sleep." },
    { word: "Anaesthetist", definition: "a specialist doctor who administers anaesthesia and monitors the patient." },
    { word: "Anal sphincter", definition: "consists of ring-like muscles surrounding the anus that help keep it closed and control bowel movements." },
    { word: "Anaphylaxis", definition: "a severe, life-threatening allergic reaction." },
    { word: "Anomaly scan", definition: "20-week ultrasound scan to check the baby’s development." },
    { word: "Antiphospholipid syndrome", definition: "autoimmune disease that increases the risk of blood clots." },
    { word: "Antenatal", definition: "prenatal; means before birth." },
    { word: "Anthracyclines", definition: "type of medication used to treat cancer." },
    { word: "Antibiotics", definition: "medications used to treat or prevent infections caused by bacteria." },
    { word: "Antibody", definition: "a protein produced by the immune system that fights unwanted substances that enter the body." },
    { word: "Anticoagulant medication", definition: "a medication that stops the blood from clotting." },
    { word: "Anti-D", definition: "an injection given to Rhesus-negative women to prevent blood group complications with the baby." },
    { word: "Antigen", definition: "a substance that triggers the immune system to produce antibodies against it." },
    { word: "Anti-inflammatory drugs", definition: "medications that reduce inflammation, pain, and fever." },
    { word: "Antiretroviral drugs/therapy", definition: "medications used to treat viral infections, most commonly HIV." },
    { word: "Antispasmodic drugs", definition: "medicines used to suppress muscle spasms; i.e., for stomach cramps." },
    { word: "Anus", definition: "the opening of the rectum to the outside of the body; it is where stool leaves the body." },
    { word: "Apnoea", definition: "temporary stopping of breathing" },
    { word: "Arthritis", definition: "inflammation of one or more joints, causing pain and stiffness." },
    { word: "Arrhythmia", definition: "an irregular heartbeat." },
    { word: "Assisted birth", definition: "a birth where tools like forceps or a vacuum are used to help deliver the baby." },
    { word: "Assisted conception", definition: "medical treatments used to help a person become pregnant; i.e., IVF." },
    { word: "Ascites", definition: "a buildup of fluid in the abdomen causing a swollen belly." },
    { word: "Autoimmune response", definition: "when the body's immune system mistakenly attacks its own healthy cells." },

    { word: "Bacteria", definition: "one-celled organisms; i.e., some are helpful, others cause infection." },
    { word: "Bacterial vaginosis", definition: "an overgrowth of bacteria in the vagina, causing discharge or odor." },
    { word: "Benign", definition: "a condition, tumor, or growth that is not cancerous." },
    { word: "Bicornuate uterus", definition: "also known as heart-shaped womb; s uterus describes an irregular shape of the uterus." },
    { word: "Bile acids", definition: "chemicals made in the liver that help the body digest fats." },
    { word: "Bilirubin", definition: "yellow pigment from breakdown of red blood cells." },
    { word: "Biopsy", definition: "a procedure to remove cells, tissue or fluid for examination by a medical pathologist." },
    { word: "Birth asphyxia", definition: "a medical condition resulting from a lack of oxygen to a newborn during birth." },
    { word: "Bladder", definition: "a hollow, spherical-shaped organ that holds urine." },
    { word: "Bladder training", definition: "a type of therapy to help improve control over urination." },
    { word: "Blood group", definition: "a classification of blood based on the presence of specific antigens (e.g., Type A, B, O)." },
    { word: "Body mass index", definition: "medical screening tool that measures the ratio of the height to the weight to estimate the amount of body fat." },
    { word: "Brachial plexus injury", definition: "damage to the nerves that send signals from the spine to the shoulder, arm, and hand." },
    { word: "Bradycardia", definition: "a slow heart rate." },
    { word: "BRCA", definition: "genes (BRCA1 and BRCA2) that, when mutated, increase the risk of breast and ovarian cancer." },
    { word: "Breech position", definition: "when a baby's feet or buttocks are positioned to come out of the vagina first." },
    { word: "Bronchitis", definition: "when the airways leading to the lungs (trachea and bronchi) get inflamed and fill with mucus." },
    { word: "Bronchodilator", definition: "help relieve asthma, COPD and other lung condition symptoms by relaxing the muscles around your airways and helping clear mucus from your lungs." },

    { word: "CA125", definition: "a protein found in the blood that can be a marker for ovarian cancer." },
    { word: "Caesarean birth", definition: "a surgical procedure used to deliver a baby through incisions in the abdomen and uterus." },
    { word: "Cancer", definition: "disease where abnormal cells divide uncontrollably and spread to the other parts of the body." },
    { word: "Candida albicans", definition: "a microscopic fungus that naturally lives in and on the body." },
    { word: "Cardiotocography", definition: "a technical means of recording the fetal heartbeat and uterine contractions." },
    { word: "Carcinoma", definition: "cancer that forms in epithelial tissue." },
    { word: "Catabolism", definition: "breakdown of complex substances in the body" },
    { word: "Catheter", definition: "a flexible tube used to drain fluid from the body; i.e., to empty the bladder." },
    { word: "Cell", definition: "the basic building blocks of all living things." },
    { word: "Cephalhaematoma", definition: "a collection of blood under the scalp of a newborn, often from birth pressure." },
    { word: "Cervical screening", definition: "a test to check the health of the cervix; i.e., a Smear Test or Pap test." },
    { word: "Cervix", definition: "a small canal that connects the uterus and vagina." },
    { word: "Chickenpox", definition: "a highly contagious viral infection causing an itchy, blister-like rash." },
    { word: "Chignon", definition: "temporary swelling on a baby's head caused by a vacuum extraction (ventouse) during birth." },
    { word: "Chlamydia trachomatis", definition: "also known as STDs, STIs or venereal disease, sexually transmitted infections are caused by bacteria, viruses or parasites" },
    { word: "Cholesterol", definition: "a waxy, fat-like substance (lipid) that does many essential jobs in the body." },
    { word: "Chocolate cysts", definition: "ovarian cysts filled with old blood." },
    { word: "Chorioamnionitis", definition: "an infection of the placenta and the amniotic fluid." },
    { word: "Chromosomal abnormality", definition: "a missing, extra, or irregular portion of chromosomal DNA." },
    { word: "Chromosomes", definition: "a thread-like structure in the cell nucleus that carry genetic information." },
    { word: "Chronic", definition: "something that continues over an extended period of time." },
    { word: "Cirrhosis", definition: "permanent scarring that damages the liver and interferes with its functioning." },
    { word: "Clear margins", definition: "when the edges of surgically removed tissue are free from cancer cells." },
    { word: "Clinical guidelines", definition: "recommendations on how to diagnose and treat a medical condition." },
    { word: "Clitoris", definition: "a small, sensitive part of the female genitals." },
    { word: "Cyanosis", definition: "medical term for when the skin, lips or nails turn blue due to a lack of oxygen in the blood." },
    { word: "Cachexia", definition: "a condition that causes significant weight loss and muscle loss." },

    { word: "Dilatation and evacuation", definition: "a surgical procedure to remove tissue from the uterus after a miscarriage or for abortion." },
    { word: "Deep vein thrombosis", definition: "occurs when a blood clot forms in one or more of the deep veins in the body, usually in the legs." },
    { word: "Delayed cord clamping", definition: "waiting a short time before cutting the umbilical cord after birth." },
    { word: "Delayed miscarriage", definition: "when the embryo or fetus has died, but the body has not yet expelled it." },
    { word: "Delivery", definition: "the process of giving birth to a baby." },
    { word: "Depression", definition: "a mood disorder causing a persistent feeling of sadness and loss of interest." },
    { word: "Dehydration", definition: "occurs when the body uses or loses more fluid than it takes in." },
    { word: "Diabetes", definition: "a disease that occurs when the blood glucose is too high." },
    { word: "Diabetes Type 1", definition: "a lifelong autoimmune disease that prevents the pancreas from making insulin, a hormone." },
    { word: "Diabetes Type 2", definition: "happens when the body can’t use insulin properly and/ or doesn’t make enough of it." },
    { word: "Diagnosis", definition: "the process of determining the nature of a disease and disorder from its sign and symptoms." },
    { word: "Diathermy", definition: "a treatment that helps relax muscles and joints, reduce inflammation and swelling, and improve blood circulation." },
    { word: "Dilatation", definition: "the action or condition of becoming wider, larger, or more open." },
    { word: "Discharge letter", definition: "a summary of hospital care given to a patient when they are sent home." },
    { word: "Disease", definition: "a disorder of structure or function in a human, especially one that produces specific symptoms." },
    { word: "Diuresis", definition: "a condition in which the kidneys filter too much bodily fluid." },
    { word: "Donor insemination", definition: "a fertility treatment that involves using sperm from a donor." },
    { word: "Doppler", definition: "an ultrasound provides information about the speed and direction of blood flow through arteries and veins." },
    { word: "Dysmenorrhoea", definition: "painful menstrual period." },
    { word: "Dyspareunia", definition: "genital pain during or after sexual intercourse." },
    { word: "Dysphagia", definition: "medical term for difficulty swallowing." },
    { word: "Dyspnoea", definition: "medical term for the feeling of not being able to get enough air." },

    { word: "Ectopic pregnancy", definition: "when a fertilized egg implants outside the uterus, usually in a fallopian tube." },
    { word: "Early miscarriage", definition: "spontaneous loss of a fetus before the 20th week of pregnancy." },
    { word: "Early pregnancy assessment unit", definition: "a specialist clinic for women experiencing problems in early pregnancy." },
    { word: "Eclampsia", definition: "seizures that occur in pregnant women with preeclampsia." },
    { word: "Electrocoagulation", definition: "using heat from an electric current to seal blood vessels or destroy tissue." },
    { word: "Embolism", definition: "an obstruction or blockage in a blood vessel." },
    { word: "Embryo", definition: "the early stage of a developing human, from fertilization until the 8th week of pregnancy." },
    { word: "Emergency cesarean delivery", definition: "an operation to give birth to your baby through a cut in the abdomen." },
    { word: "Encephalitis", definition: "inflammation of the brain." },
    { word: "Endometrial biopsy", definition: "endometrial biopsy is a medical procedure in which the healthcare provider removes a small piece of tissue from the lining of the uterus (the endometrium) to examine under a microscope." },
    { word: "Endocrine system", definition: "in charge of creating and releasing hormones to maintain countless bodily functions." },
    { word: "Erythema", definition: "redness of the skin" },

    { word: "Fallopian tubes", definition: "pair of hollow, muscular ducts located between the ovaries and uterus." },
    { word: "Fecundity", definition: "the biological ability to reproduce or produce offspring." },
    { word: "Female genital mutilation", definition: "procedures involving partial or total removal of female external genitalia for non-medical reasons." },
    { word: "Fertilisation", definition: "when sperm and an egg cell join together." },
    { word: "Fertility", definition: "the natural capability to produce offspring." },
    { word: "Fertility drugs", definition: "medications used to stimulate ovulation or increase the chance of pregnancy." },
    { word: "Fertility problem / Infertility", definition: "difficulties or the inability to conceive after a year of trying." },
    { word: "Fetus", definition: "the developing human from the 9th week of pregnancy until birth." },
    { word: "Fetal medicine specialist", definition: "a doctor who specializes in the care of the baby while it is in the womb." },
    { word: "Fibroids", definition: "non-cancerous growths in or around the uterus." },
    { word: "Fimbriae", definition: "small, finger-like projections at the end of the fallopian tubes." },
    { word: "First-degree tear", definition: "an injury to the tissue around the vagina and anus that can happen during childbirth." },
    { word: "Flexed breech position", definition: "when the baby is bottom-first with hips and knees bent." },
    { word: "Folic acid", definition: "used for preventing and treating low blood levels of folate (folate deficiency) and high blood levels of homocysteine (hyperhomocysteinemia)." },
    { word: "Follicle", definition: "small sacs filled with fluid inside a woman's ovaries." },
    { word: "Follicle-stimulating hormone", definition: "a hormone that helps control the menstrual cycle and egg production." },
    { word: "Footling breech", definition: "when the baby is positioned with one or both feet coming out first." },
    { word: "Forceps delivery", definition: "a form of assisted delivery that can help mothers deliver their babies vaginally when labor is not progressing normally." },
    { word: "Fourth-degree tear", definition: "a tear that extends through the perineum into the anal sphincter and rectum." },
    { word: "Fracture", definition: "medical definition for a broken bone." },
    { word: "Febrile", definition: "having fever." },
    { word: "Fistula", definition: "connection between two parts of the body that don't normally connect." },
    { word: "Flatulence", definition: "passing gas through the anus." },
    { word: "Fibrosis", definition: "occurs when lung tissue becomes damaged and scarred." },

    { word: "Gamma globulin", definition: "a part of the blood that contains antibodies to help fight infection." },
    { word: "Gastroenteritis", definition: "inflammation of the stomach and intestines brought on by a virus or bacteria." },
    { word: "Gastrointestinal", definition: "relating to the stomach and the intestines." },
    { word: "Gastritis", definition: "inflammation of the lining of the stomach." },
    { word: "Gene", definition: "the basic physical and functional unit of heredity." },
    { word: "Genetic", definition: "the study of genes, genetic variation, and heredity in organisms." },
    { word: "Genetic counselling", definition: "the study of genes, genetic variation, and heredity in organisms." },
    { word: "General anaesthesia", definition: "medication that makes you fully unconscious and unable to feel pain." },
    { word: "Genitals", definition: "the external reproductive organs." },
    { word: "Genital herpes", definition: "a sexually transmitted infection or STI, also called a sexually transmitted disease or STD." },
    { word: "Gestation", definition: "the period of time between conception and birth." },
    { word: "Gestational age", definition: "common term used during pregnancy to describe how far along the pregnancy is." },
    { word: "Gestational diabetes", definition: "high blood sugar that develops or is first recognized during pregnancy." },
    { word: "Gestational Trophoblastic Disease", definition: "a group of rare tumors that involve abnormal growth of cells inside the uterus." },
    { word: "Gestational Trophoblastic Neoplasia", definition: "a collective term for gestational trophoblastic diseases that originate from placental tissue and invade locally or metastasize." },
    { word: "Glucose", definition: "the main sugar found in your blood." },
    { word: "Gonadotrophin-releasing hormone agonist", definition: "stimulate the production of follicle-stimulating hormone and luteinizing hormone." },
    { word: "Gonadotrophins", definition: "make the sex hormones testosterone, estrogen and progesterone." },
    { word: "Gonorrhoea", definition: "a bacterial sexually transmitted infection." },
    { word: "Goitre", definition: "a condition where the thyroid gland grows larger." },
    { word: "Graduated elastic compression stocking", definition: "tight stockings used to prevent blood clots in the legs." },
    { word: "Group B streptococcus", definition: "a type of bacteria commonly carried in the human gut or vagina." },
    { word: "Guideline", definition: "a set of rules or suggestions for best medical practice." },
    { word: "Gynaecologist", definition: "a doctor who specializes in the female reproductive system." },
    { word: "Granuloma", definition: "an area of tightly clustered immune cells, or inflammation, in the body." },

    { word: "Highly active antiretroviral therapy", definition: "a combination of medications used to treat HIV" },
    { word: "Haematologist", definition: "a doctor who specializes in blood disorders." },
    { word: "Haemolysis", definition: "destruction of red blood cells." },
    { word: "Haemorrhage", definition: "an escape of blood from a ruptured blood vessel; heavy bleeding." },
    { word: "Hematoma", definition: "closed wound where blood collects and fills a space inside the body because it can't flow or drain out." },
    { word: "Heart palpitations", definition: "a feeling like the heart is missing heartbeats, racing or pounding." },
    { word: "HELLP syndrome", definition: "a rare pregnancy complication that mainly affects the blood and liver." },
    { word: "Hematuria", definition: "blood in urine." },
    { word: "Heparin", definition: "an anticoagulant (“blood thinner”) that stops the blood from forming blood clots or making them bigger." },
    { word: "Herpes", definition: "a viral infection causing sores or blisters (oral or genital)." },
    { word: "Human chorionic gonadotrophin", definition: "a hormone produced by the placenta during pregnancy." },
    { word: "Human immunodeficiency virus", definition: "infects and destroys cells of your immune system, making it hard to fight off other diseases." },
    { word: "Human papillomavirus", definition: "a common virus that can affect different parts of your body." },
    { word: "Hyperglycemia", definition: "too much sugar (glucose) in your blood." },
    { word: "Hypermobility syndrome", definition: "genetic condition that involves extreme flexibility along with pain and other symptoms." },
    { word: "Hyperprolactinaemia", definition: "having a high level of prolactin in the blood." },
    { word: "Hypertension", definition: "also known as high blood pressure; means the force of blood pushing against the artery walls is consistently too high." },
    { word: "Hypoglycemia", definition: "low blood sugar." },
    { word: "Hypotension", definition: "also known as low blood pressure; means the force of the blood pushing against the artery walls is too low." },
    { word: "Hypothalamus", definition: "a region of the brain that controls hormones and body temperature." },
    { word: "Hypoxia", definition: "low levels of oxygen in the body tissues." },
    { word: "Hysterectomy", definition: "a surgery to remove a woman's womb (uterus)." },
    { word: "Hysterosalpingo-contrast-sonography", definition: "an ultrasound procedure to check if the fallopian tubes are open." },
    { word: "Hysterosalpingogram", definition: "an X-ray dye test that allows the healthcare provider to see the uterus and fallopian tubes." },
    { word: "Hysteroscopy", definition: "a procedure that allows a surgeon to look inside of the uterus in order to diagnose and treat the causes of abnormal bleeding." },

    { word: "Immune system", definition: "is a complex network of cells, tissues, and organs." },
    { word: "Immunity", definition: "the ability of an organism to resist a particular infection." },
    { word: "Immunotherapy", definition: "treatment that uses the body's immune system to fight disease." },
    { word: "Implantation", definition: "when a fertilized egg attaches to the lining of the uterus." },
    { word: "In vitro fertilisation", definition: "the joining of a woman's egg and a man's sperm in a laboratory dish." },
    { word: "Incomplete miscarriage", definition: "when some, but not all, pregnancy tissue has left the uterus." },
    { word: "Incontinence", definition: "the loss of control over the bladder or bowels." },
    { word: "Induction of labour", definition: "a common obstetric intervention that stimulates the onset of labor using artificial methods." },
    { word: "Infectious", definition: "producing or capable of producing infection." },
    { word: "Inflammation", definition: "is the immune system's response to injury or infection; physical condition in which part of the body becomes reddened, swollen, and painful." },
    { word: "Informed decision", definition: "a choice made after being given all the facts and risks." },
    { word: "Infusion", definition: "the slow injection of a substance (like medicine) into a vein." },
    { word: "Intensive care unit", definition: "a special area in a hospital or healthcare facility for people who have a life-threatening illness or injury." },
    { word: "Interstitial cystitis", definition: "also known as bladder pain syndrome; a long-term discomfort, pain or pressure in the bladder area." },
    { word: "Incision", definition: "surgical cut." },
    { word: "Intubation", definition: "insertion of tube into airway." },
    { word: "Ischemia", definition: "a condition in which some parts of the body don't get enough blood." },
    { word: "Iatrogenic", definition: "caused by medical treatment." },
    { word: "Idiopathic", definition: "medical term that describes a condition with an unknown cause." },

    { word: "Jaundice", definition: "when the skin, sclera (whites of the eyes) and mucous membranes turn yellow." },
    { word: "Joint effusion", definition: "where the fluids in the tissues around the joint increase causing the knee, shoulder, ankle or other joint swells up." },

    { word: "Karyotype", definition: "an individual's complete set of chromosomes." },
    { word: "Ketonuria", definition: "the presence of ketones in the urine." },
    { word: "Kyphosis", definition: "a spinal condition where the spine curves outward more than it should." },

    { word: "Laceration", definition: "a tear or rip somewhere on or in the body." },
    { word: "Lesion", definition: "abnormal tissue damage." },
    { word: "Lethargy", definition: "feelings of fatigue as well as a lack of mental or physical motivation." },
    { word: "Leukopenia", definition: "low white blood cell count." },
    { word: "Lymphoma", definition: "term for a group of blood cancers in the lymphatic system." },

    { word: "Menstruation", definition: "is the monthly shedding of the lining of the uterus." },
    { word: "Malaise", definition: "generally feel unwell." },
    { word: "Melanoma", definition: "which means 'black tumor,' is the most dangerous type of skin cancer." },
    { word: "Metastasis", definition: "when cancer spreads beyond the place where it started to other areas of the body." },
    { word: "Myalgia", definition: "muscle pain." },
    { word: "Myocardial infarction", definition: "also known as heart attack; blood flow to the heart is greatly reduced or blocked, leading to heart muscle damage." },

    { word: "Neonatal unit", definition: "a hospital department for the care of newborn babies who are ill or premature." },
    { word: "Neonatalologist", definition: "a doctor who specializes in the care of newborn infants." },
    { word: "Neural tube defects", definition: "are birth defects of the brain, spine or spinal cord that happen in fetuses within the first month of pregnancy." },
    { word: "Nausea", definition: "feeling an urge to vomit." },
    { word: "Necrosis", definition: "medical term for the death of the body tissue." },
    { word: "Neoplasm", definition: "a mass of abnormal cells that form in the body." },
    { word: "Neuropathy", definition: "injury to one or more peripheral nerves." },

    { word: "Obstetrician", definition: "a physician who specializes in delivering babies." },
    { word: "Oedema", definition: "medical term for swelling from fluid trapped in the body's tissues" },
    { word: "Oestrogen", definition: "a group of female sex hormones that plays a key role in female reproductive health." },
    { word: "Oligohydramnios", definition: "a condition where there is too little amniotic fluid around the fetus." },
    { word: "Oliguria", definition: "low urine output." },
    { word: "Oocyte donation", definition: "when a woman donates eggs to help another person conceive." },
    { word: "Ovarian hyperstimulation syndrome", definition: "occurs in women who receive fertility treatments that stimulate their ovaries to produce a large number of eggs." },
    { word: "Ovaries", definition: "small glands located on either side of the uterus; produce eggs and hormones for menstruation and pregnancy." },
    { word: "Ovulation", definition: "when the ovary releases an egg; happens around the 14th day of a 28-day menstrual cycle." },
    { word: "Osteoarthritis", definition: "a type of arthritis that happens when cartilage in the joints wears down." },
    { word: "Osteoporosis", definition: "a disease that weakens the bones and makes them much more likely to fracture" },
    { word: "Oxytocics", definition: "a natural hormone that stimulates uterine contractions in childbirth and lactation after childbirth." },

    { word: "Paediatrician", definition: "a doctor who focuses on the health of infants, children, adolescents and young adults." },
    { word: "Pathogen", definition: "any organism that causes disease." },
    { word: "Peer review", definition: "evaluation of scientific or medical work by others in the same field." },
    { word: "Pelvic", definition: "the bony structure inside the hips, buttocks and pubic region." },
    { word: "Pelvic congestion", definition: "involves problems with blood flow in the pelvic veins." },
    { word: "Pelvic floor muscles", definition: "help stabilize the core while assisting with bodily functions, like pooping, peeing and having sex." },
    { word: "Pelvic inflammatory disease", definition: "an infection that occurs in the uterus, fallopian tubes or ovaries." },
    { word: "Perforation", definition: "hole in an organ." },
    { word: "Perineal tear", definition: "an injury to the tissue around the vagina and anus that can happen during childbirth." },
    { word: "Perineum", definition: "the thin layer of skin between the genitals (vaginal opening or scrotum) and anus." },
    { word: "Peritoneum", definition: "a membrane that lines the inside of the abdomen and pelvis" },
    { word: "Pessaries", definition: "a removable device that goes inside the vagina." },
    { word: "Phlebitis", definition: "inflammation of the vein." },
    { word: "Physiotherapy", definition: "a treatment that helps improve how the body performs physical movements." },
    { word: "Pituitary gland", definition: "a small gland in the brain that makes and controls many hormones; it also controls many of the other endocrine glands." },
    { word: "Placenta", definition: "a temporary organ that connects the fetus to the uterus during pregnancy." },
    { word: "Placenta accreta", definition: "a condition where the placenta (the food and oxygen source for a fetus) grows too deeply into the wall of the uterus." },
    { word: "Placenta praevia", definition: "a condition during pregnancy where the placenta blocks all or part of the baby's exit from the vagina." },
    { word: "Platelets", definition: "tiny cell fragments in the blood that help with clotting." },
    { word: "Pneumonia", definition: "inflammation and fluid in the lungs caused by a bacterial, viral or fungal infection." },
    { word: "Polycystic ovaries syndrome", definition: "a complex endocrine and metabolic disorder, typically characterized by anovulation, infertility, obesity, insulin resistance, and polycystic ovaries." },
    { word: "Polyhydramnios", definition: "having too much amniotic fluid around the fetus." },
    { word: "Polyp", definition: "tissue growths that most often look like small, flat bumps or tiny mushroom-like stalks." },
    { word: "Post-mortem", definition: "an examination of a body after death to determine the cause." },
    { word: "Postnatal", definition: "refers to the period after childbirth." },
    { word: "Pre-eclampsia", definition: "a serious pregnancy complication that causes persistent high blood pressure." },
    { word: "Pregnancy test", definition: "test used to determine if a woman is pregnant." },
    { word: "Premature birth", definition: "means a baby is born too early." },
    { word: "Progesterone", definition: "a hormone that supports menstruation and maintaining a pregnancy." },
    { word: "Prognosis", definition: "the likely outcome of a disease, injury or illness." },
    { word: "Prolactin", definition: "a polypeptide hormone responsible for lactation, breast development, and hundreds of other actions needed to maintain homeostasis." },
    { word: "Prolapse", definition: "a common medical condition that occurs when the structures designed to keep organs in place weaken or stretch." },
    { word: "Prostaglandin", definition: "are hormone-like substances that affect several bodily functions, including inflammation, pain and uterine contractions" },
    { word: "Proteinuria", definition: "protein in the urine happens when proteins leak into the pee." },
    { word: "Pubic", definition: "a joint sandwiched between the left pubic bone and the right pubic bone." },
    { word: "Pudendal block", definition: "an injection in the pelvic region that can provide temporary pain relief." },
    { word: "Pulmonary embolism", definition: "a blood clot in the lung that creates a blockage." },

    { word: "Quadriplegia", definition: "paralysis that affects all a person's limbs." },

    { word: "Randomised controlled trial", definition: "prospective studies that measure the effectiveness of a new intervention or treatment." },
    { word: "Rectocele", definition: "a condition in which weakened muscles in the pelvis cause the rectum to sag against the vaginal wall." },
    { word: "Rectum", definition: "part of the large intestine that lies between the colon and the anus." },
    { word: "Recurrent miscarriage", definition: "the loss of three or more consecutive pregnancies." },
    { word: "Remission", definition: "a period of time when disease symptoms lessen or go away." },
    { word: "Reproductive organs", definition: "the bodily structures responsible for sexual reproduction, producing gametes (sperm/eggs) and sex hormones, and facilitating fertilization." },
    { word: "Resection", definition: "surgical removal of tissue." },
    { word: "Respiration", definition: "breathing process." },
    { word: "Retrovirus", definition: "a virus that uses RNA as its genomic material." },
    { word: "RhD antigen", definition: "a protein found on the surface of red blood cells (Rhesus factor)." },
    { word: "Rigor", definition: "an episode of shaking or exaggerated shivering which can occur with a high fever." },
    { word: "Risk", definition: "the possibility that something unpleasant or dangerous will happen." },
    { word: "Rupture of membranes", definition: "commonly called “water breaking”; when the leak of amniotic fluid before labor begins." },

    { word: "Secretion", definition: "release of substances." },
    { word: "Sepsis", definition: "a life-threatening reaction to an infection that causes the immune system to harm healthy tissues and organs" },
    { word: "Scientific evidence", definition: "information used to support or prove a medical theory or treatment." },
    { word: "Screening", definition: "to identify people in an apparently healthy population who are at higher risk of a health problem or condition." },
    { word: "Special care baby unit", definition: "a ward for babies who need extra care but are not critically ill." },
    { word: "Speculum", definition: "an instrument used to widen an opening of the body to make it easier to look inside." },
    { word: "Sperm", definition: "male reproductive cells." },
    { word: "Spina bifida", definition: "a condition that occurs when the spine and spinal cord don't form properly." },
    { word: "Sporadic", definition: "occurring at irregular intervals or only in a few places; scattered or isolated." },
    { word: "Stenosis", definition: "refer to the abnormal narrowing of any channel or passageway in the body" },
    { word: "Sterilisation", definition: "a permanent method of contraception; i.e., 'tying the tubes.'" },
    { word: "Steroids", definition: "prescription medications that reduce inflammation in the body." },
    { word: "Stool", definition: "material in a bowel movement." },
    { word: "Sutures", definition: "medical tools used by doctors and surgeons to close a wound." },
    { word: "Symptom", definition: "physical or mental feature indicating a condition or disease." },
    { word: "Syndrome", definition: "an exclusively medical term and came to mean anything unusual, abnormal, bizarre, or humorous." },
    { word: "Syncope", definition: "a broad medical term for fainting." },

    { word: "Thrombophilia", definition: "a condition that makes the blood more likely to form clots." },
    { word: "Tachycardia", definition: "medical term for a heart rate over 100 beats a minute." },
    { word: "Temperature", definition: "the degree of internal heat of a person's body." },
    { word: "Testosterone", definition: "a hormone that stimulates development of male secondary sexual characteristics." },
    { word: "Thrombosis", definition: "is the formation of a blood clot (thrombus) inside one of your blood vessels or a chamber of your heart." },
    { word: "Tissue", definition: "group of similar cells." },
    { word: "Thrush", definition: "a fungal (yeast) infection that can grow in your mouth, throat and other parts of the body." },
    { word: "Tocolysis", definition: "the use of medications to stop or delay preterm labor." },
    { word: "Toxaemia", definition: "a condition where there is a presence of bacterial toxins in the blood." },
    { word: "Toxicity", definition: "harmful effects of substances." },
    { word: "Trachea", definition: "known as windepipe; the tube that connects the voice box with your bronchi in the lungs" },
    { word: "Transfusion", definition: "common procedure in which a person receives donated blood or blood components through an intravenous (IV) line." },
    { word: "Tumor", definition: "a mass of abnormal cells that form in your body." },

    { word: "Uremia", definition: "a buildup of waste products in the blood that occurs as a result of untreated kidney failure" },
    { word: "Urticaria", definition: "raised and splotchy areas of skin that can be caused by an allergic reaction to something." },
    { word: "Urolithiasis", definition: "a condition that occurs when these stones exit the renal pelvis and move into the remainder of the urinary collecting system." },
    { word: "Uveitis", definition: "inflammation of your uvea, the middle layer of your eye." },
    { word: "Umbilicus", definition: "medical term for belly button or navel." },

    { word: "Vasoconstriction", definition: "when the muscles around the blood vessels tighten to make the space inside smaller." },
    { word: "Vasodilation", definition: "when blood vessels in the body widen, allowing more blood to flow through them and lowering the blood pressure." },
    { word: "Venipuncture", definition: "collection of blood from a vein." },
    { word: "Viremia", definition: "viruses present in the bloodstream." },

    { word: "Wheal", definition: "localized skin edema (raised swelling)." },
    { word: "Wernicke’s aphasia", definition: "language disorder that affects the ability to make sense when speaking." },
    { word: "Wasting syndrome", definition: "a condition that causes significant weight loss and muscle loss." },
    { word: "Wolff-Parkinson-White syndrome", definition: "heart condition present at birth" },
    { word: "White blood cells (Leukocytes)", definition: "are responsible for protecting your body from infection." },

    { word: "Xeroderma", definition: "abnormally dry skin." },
    { word: "Xerostomia", definition: "dry mouth; salivary glands in the mouth don't make enough saliva to keep the mouth wet." },
    { word: "Xanthoma", definition: "a skin condition in which certain fats build up under the surface of the skin." },
    { word: "Xanthopsia", definition: "an overriding yellow bias in vision, can be provoked by many disorders other than the reddish-brown filter of nuclear sclerosis." },
    { word: "X-linked inheritance", definition: "genetic transmission via X chromosome." },

    { word: "Yersiniosis", definition: "a bacterial infection, results from handling or eating raw or undercooked pork." },
    { word: "Yolk sac", definition: "umbilical vesicle, is a small membranous structure outside the embryo with various functions during embryonic development." },
    { word: "Yaws", definition: "a chronic disfiguring and debilitating childhood infectious disease." },
    { word: "Yohimbine", definition: "an indole alkaloid derived from the bark of the Central African yohimbe tree that is widely used as therapy for erectile dysfunction." },

    { word: "Zygote", definition: "fertilized egg cell." },
    { word: "Zoster", definition: "viral infection that causes a painful rash and nerve damage." },
    { word: "Zollinger-ellision syndrome", definition: "a condition in which one or more tumors grow in the pancreas or small intestine." },
    { word: "Zoophobia", definition: "an extreme fear of a specific animal or all animals." },
    { word: "Zymogen", definition: "inactive enzyme precursor." }
];